### ISSUE TITLE
C-WAP repository

### ISSUE THREAD

**Issue by danstrange** [CFSAN-Biostatistics/WW-SC2-variant-estimations#1]
Hi, was brought here by the FDA wastewater surveillance for SARS-CoV-2 variants website, looking for the C-WAP processing pipeline, but instead got 404 (not found) error for the repository link and don't see it in the list of CFSAN-Biostatics repositories.  Has the C-WAP pipeline repository been renamed or removed etc.?  Thanks.

**Comment by crashfrog** [comment]
We’ve temporarily set it to private while we review it for potentially sensitive information. It should be public again in about a week. Sorry for the inconvenience!

**Comment by strangemandan** [comment]
> We’ve temporarily set it to private while we review it for potentially sensitive information. It should be public again in about a week. Sorry for the inconvenience!
> […](#)
> On Sep 21, 2022 at 3:52 AM +0700, strangemandan ***@***.***>, wrote: Hi, was brought here by the FDA wastewater surveillance for SARS-CoV-2 variants website, looking for the C-WAP processing pipeline, but instead got 404 (not found) error for the repository link and don't see it in the list of CFSAN-Biostatics repositories. Has the C-WAP pipeline repository been renamed or removed etc.? Thanks. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Okay, no problem at all.  Happy to know it will be back soon.  Thanks for that!

**Comment by strangemandan** [comment]
Okay, no problem at all. Happy to know it will be back soon. Thanks for that!

**Comment by danstrange** [comment]
Okay, no problem at all. Happy to know it will be back soon. Thanks for that!

> We’ve temporarily set it to private while we review it for potentially sensitive information. It should be public again in about a week. Sorry for the inconvenience!
